// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusicAtoutV1_Savio.Models;

public partial class Oeuvre
{
    public int IdOeuvre { get; set; }

    public int IdType { get; set; }

    public int IdCompositeur { get; set; }

    public string TitreOeuvre { get; set; }

    public int? AnComposition { get; set; }

    public string Texte { get; set; }

    public virtual Compositeur IdCompositeurNavigation { get; set; }

    public virtual Typeoeuvre IdTypeNavigation { get; set; }
}