// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusicAtoutV1_Savio.Models;

public partial class Salle
{
    public int IdBati { get; set; }

    public int NumSalle { get; set; }

    public string NomSalle { get; set; }

    public int? Capacite { get; set; }

    public int? Superficie { get; set; }

    public virtual Batiment IdBatiNavigation { get; set; }

    public virtual ICollection<Typeoeuvre> IdTypes { get; set; } = new List<Typeoeuvre>();
}