// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusicAtoutV1_Savio.Models;

public partial class Style
{
    public int IdStyle { get; set; }

    public string LibStyle { get; set; }

    public int? DateDebut { get; set; }

    public int? DateFin { get; set; }

    public virtual ICollection<Compositeur> Compositeurs { get; set; } = new List<Compositeur>();
}