// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusicAtoutV1_Savio.Models;

public partial class Utilisateur
{
    public string IdUtilisateur { get; set; }

    public string Passwd { get; set; }

    public int? Droits { get; set; }

    public bool? Actif { get; set; }

    public int? Nbessais { get; set; }
}